### ISSUE TITLE
java.lang.IllegalStateException: Toolkit not initialized

### ISSUE THREAD

**Issue by starksm64** [quarkiverse/quarkus-fx#22]
I'm just capturing this issue for discussion as in general the infamous "Toolkit not initialized" shows up many different ways, and I see there still is no javafx.application.Platform.isRunning() type method to check if the platform has initialized. 

In this particular case I have a `@Scheduled` activity that I can simply add an initial delay to, but in general, how CDI components interact with javafx during startup needs hacks to wait for initialization.

Maybe there needs to be a quarkus-fx runnable event queue that can take care of delaying submitting the tasks until the application is fully running.

```
2024-02-05 14:04:45,011 ERROR [io.qua.sch.com.run.StatusEmitterInvoker] (executor-thread-1) Error occurred while executing task for trigger IntervalTrigger [id=1_com.si.totp.app.ClockEvents#increment, interval=30000]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Toolkit not initialized
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)
        at java.base/java.util.concurrent.CompletableFuture$MinimalStage.whenComplete(CompletableFuture.java:2948)
        at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:24)
        at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask.doInvoke(SimpleScheduler.java:416)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.handle(SimpleScheduler.java:397)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.handle(SimpleScheduler.java:393)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
        at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:581)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: Toolkit not initialized
        at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:436)
        at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:431)
        at javafx.application.Platform.runLater(Platform.java:168)
        at com.si.totp.app.ClockEvents.increment(ClockEvents.java:27)
        at com.si.totp.app.ClockEvents_ClientProxy.increment(Unknown Source)
        at com.si.totp.app.ClockEvents_ScheduledInvoker_increment_1c777d19e98d20799c6b72c29b26289f3f771250.invokeBean(Unknown Source)
        ... 15 more
```

**Comment by CodeSimcoe** [comment]
Do you have a small sample app that could be used to witness this ?

**Comment by CodeSimcoe** [comment]
Something could indeed be done. Maybe many different things... If you have any specification in mind...

Regarding your @Scheduled issue, you could provide a `SkipPredicate` similar to the builtin `ApplicationNotRunning` but observing `@PrimaryStage` event.

**Comment by starksm64** [comment]
So my [quarkus-fx](https://github.com/starksm64/quarkus-fx.git) fork has a forced example of the problem in the samples/clock subdirectory.

What happens is that there is a race condition between scheduler thread and the javafx launcher thread. See the points labelled with // (1), // (2), and // (3):

```
2024-02-06 17:12:18,141 INFO  [io.quarkus] (main) quarkus-fx-sample-using-scheduler 999-SNAPSHOT on JVM (powered by Quarkus 3.2.10.Final) started in 0.333s. 
2024-02-06 17:12:18,141 INFO  [io.quarkus] (main) Profile prod activated. 
2024-02-06 17:12:18,145 INFO  [io.quarkus] (main) Installed features: [cdi, quarkus-fx, scheduler, smallrye-context-propagation, vertx]
java.lang.Exception: Stack trace
        at java.base/java.lang.Thread.dumpStack(Thread.java:2209)
        at io.quarkiverse.fx.QuarkusFxApplication.run(QuarkusFxApplication.java:10) // (1)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)

2024-02-06 17:12:19,084 ERROR [io.qua.sch.com.run.StatusEmitterInvoker] (executor-thread-1) Error occurred while executing task for trigger IntervalTrigger [id=1_io.quarkiverse.fx.sample.ClockEvents#timeIncrement, interval=1000]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Toolkit not initialized  // (2)
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2357)
        at java.base/java.util.concurrent.CompletableFuture$MinimalStage.whenComplete(CompletableFuture.java:2948)
        at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:24)
        at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask.doInvoke(SimpleScheduler.java:416)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.handle(SimpleScheduler.java:397)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.handle(SimpleScheduler.java:393)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
        at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:581)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: Toolkit not initialized
        at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:436)
        at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:431)
        at javafx.application.Platform.runLater(Platform.java:168)
        at io.quarkiverse.fx.RunOnFxThreadInterceptor.runOnFxThread(RunOnFxThreadInterceptor.java:23)
        at io.quarkiverse.fx.RunOnFxThreadInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at io.quarkiverse.fx.sample.ClockEvents_Subclass.timeIncrement(Unknown Source)
        at io.quarkiverse.fx.sample.ClockEvents_ClientProxy.timeIncrement(Unknown Source)
        at io.quarkiverse.fx.sample.ClockEvents_ScheduledInvoker_timeIncrement_37506911735539830375cffc7b6444bd80624f84.invokeBean(Unknown Source)
        ... 15 more

2024-02-06 17:12:19,155 WARNING [javafx] (JavaFX-Launcher) Unsupported JavaFX configuration: classes were loaded from 'unnamed module @79ca92b9'
2024-02-06 17:12:19,272 INFO  [io.qua.fx.sam.QuarkusFxApp] (JavaFX Application Thread) Begin start: java.lang.Exception
        at io.quarkiverse.fx.sample.QuarkusFxApp.start(QuarkusFxApp.java:26). // (3)
        at io.quarkiverse.fx.sample.QuarkusFxApp_Observer_start_659724dec8591b6562ac2854144bab04e342b063.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
        at io.quarkiverse.fx.FxApplication.start(FxApplication.java:19)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

...
```

// (1) this is where the quarkus main entry is being run which calls the javafx Application.launch for the javafx app.

// (2) this is where the scheduler framework has made a call into `@Scheduled` method, which calls Platform.runLater before the javafx app is initialized

// (3) this is where the thread created by the javafx Application.launch calls the io.quarkiverse.fx.FxApplication which intern fires the `@PrimaryStage` event.

The race is between (2) and (3). The scheduler has no knowledge of javafx and its requirements to initialize from (3) before any interaction with Platform.runLater() can happen.

Originally I was directly calling Platform.runLater() from the scheduler method. The use of the `@RunOnFxThread` does allow the possibility of introducing a startup condition to the `RunOnFxThreadInterceptor` that would delay the invocation until after the `io.quarkiverse.fx.FxApplication.start()` method finishes.

**Comment by CodeSimcoe** [comment]
Thanks for this sample I think it could be added it to `samples/`.
I used the following code :

```
@Scheduled(every = "1s", skipExecutionIf = FxApplicationNotRunning.class)
@RunOnFxThread
void timeIncrement() {
    sendTimeEvent();
}
```

```
@Singleton
public class FxApplicationNotRunning implements SkipPredicate {

    private volatile boolean running;

    void started(@Observes @PrimaryStage Stage stage) {
        this.running = true;
    }

    @Override
    public boolean test(ScheduledExecution execution) {
        return !running;
    }
}
```

**Comment by starksm64** [comment]
Right, there are workarounds for the scheduler case, another one being adding an initial delay. The general problem of having background threads interacting with the javafx thread during startup needs a more general solution. I'll take a look at adding condition that is set by `io.quarkiverse.fx.FxApplication` that the `RunOnFxThreadInterceptor` can use to hold all background threads until the application has completed the start method.

**Comment by starksm64** [comment]
See the latest changes in https://github.com/starksm64/quarkus-fx.git where I added a `CountDownLatch` that can be used as a startup condition and used it in the `RunOnFxThreadInterceptor`. I also renamed the clock sample to using-scheduler to be consistent with the others. If this is a direction you like I can create a proper PR.

**Comment by CodeSimcoe** [comment]
That sounds pretty legitimate.
You can open a PR
