### ISSUE TITLE
Apparent deadlock if you invoke a @RunOnFxThread method from within a controller `@FXML void initialize()` method

### ISSUE THREAD

**Issue by starksm64** [quarkiverse/quarkus-fx#60]
I have a quarkus-fx app located in the tools/tck-rewrite-fx module of the https://github.com/eclipse-ee4j/jakartaee-tck-tools repository, and I just made a change (not committed) to invoke a `@RunOnFxThread` annotated method from within the JavaFx `@FXML void initialize()` method of a controller, and this is apparently causing a deadlock as the app window fails to display. Here is the console log and the threadump. Maybe this is an obvious do not do, but I have not had a chance to look into why it is happening as yet.

```
starksm@Scotts-Mac-Studio tck-rewrite-fx % java -jar target/quarkus-app/quarkus-run.jar 
LogManager error of type GENERIC_FAILURE: Handler with name 'console' is linked to a category but not configured.
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-07-26 07:57:13 INFO  [io.quarkus] (main) tck-rewrite-fx 1.0-SNAPSHOT on JVM (powered by Quarkus 3.12.2) started in 0.401s. 
2024-07-26 07:57:13 INFO  [io.quarkus] (main) Profile prod activated. 
2024-07-26 07:57:13 INFO  [io.quarkus] (main) Installed features: [cdi, quarkus-fx]
2024-07-26 07:57:13 WARN  [javafx] (JavaFX-Launcher) Unsupported JavaFX configuration: classes were loaded from 'unnamed module @365185bd'
2024-07-26 07:57:13 SEVERE [tck.jakarta.rewrite.fx.AppController] (JavaFX Application Thread) JUL logging test at SEVERE level
2024-07-26 07:57:13 WARNING [tck.jakarta.rewrite.fx.AppController] (JavaFX Application Thread) JUL logging test at WARN level
2024-07-26 07:57:13 INFO  [tck.jakarta.rewrite.fx.AppController] (JavaFX Application Thread) JUL logging test at INFO level
2024-07-26 07:57:13 INFO  [tck.jakarta.rewrite.fx.AppController] (JavaFX Application Thread) TS_HOME: /Users/starksm/Dev/Jakarta/wildflytck/jakartaeetck
^\2024-07-26 07:57:20
Full thread dump OpenJDK 64-Bit Server VM (21.0.1+12-LTS mixed mode):

Threads class SMR info:
_java_thread_list=0x00006000022564e0, length=18, elements={
0x000000013f008200, 0x000000014e819000, 0x000000014e85ea00, 0x000000014e867200,
0x000000013e894000, 0x000000013e894800, 0x000000013e896e00, 0x000000012e808200,
0x000000013e897600, 0x000000013e814400, 0x000000014e81b400, 0x000000013f215a00,
0x000000013e98a200, 0x000000014e98c200, 0x000000010387ac00, 0x000000013ecbe600,
0x000000013ecbee00, 0x000000014ea02200
}

"main" #1 [10499] prio=5 os_prio=31 cpu=305.54ms elapsed=7.88s tid=0x000000013f008200 nid=10499 waiting on condition  [0x000000016d37e000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.1/Native Method)
        - parking to wait for  <0x0000000400800428> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@21.0.1/LockSupport.java:371)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@21.0.1/AbstractQueuedSynchronizer.java:519)
        at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@21.0.1/ForkJoinPool.java:3780)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@21.0.1/ForkJoinPool.java:3725)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitUninterruptibly(java.base@21.0.1/AbstractQueuedSynchronizer.java:1660)
        at io.quarkus.runtime.ApplicationLifecycleManager.waitForExit(ApplicationLifecycleManager.java:405)
        at io.quarkus.runtime.Quarkus.waitForExit(Quarkus.java:174)
        at io.quarkiverse.fx.QuarkusFxApplication.run(QuarkusFxApplication.java:36)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.lang.invoke.LambdaForm$DMH/0x00000008000c2800.invokeStatic(java.base@21.0.1/LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/0x00000008000c3c00.invoke(java.base@21.0.1/LambdaForm$MH)
        at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@21.0.1/Invokers$Holder)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@21.0.1/DirectMethodHandleAccessor.java:154)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@21.0.1/DirectMethodHandleAccessor.java:103)
        at java.lang.reflect.Method.invoke(java.base@21.0.1/Method.java:580)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)

"Reference Handler" #9 [22531] daemon prio=10 os_prio=31 cpu=0.62ms elapsed=7.86s tid=0x000000014e819000 nid=22531 waiting on condition  [0x000000016e4f6000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@21.0.1/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@21.0.1/Reference.java:246)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@21.0.1/Reference.java:208)

"Finalizer" #10 [23043] daemon prio=8 os_prio=31 cpu=0.10ms elapsed=7.86s tid=0x000000014e85ea00 nid=23043 in Object.wait()  [0x000000016e702000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait0(java.base@21.0.1/Native Method)
        - waiting on <0x0000000400809ec8> (a java.lang.ref.NativeReferenceQueue$Lock)
        at java.lang.Object.wait(java.base@21.0.1/Object.java:366)
        at java.lang.Object.wait(java.base@21.0.1/Object.java:339)
        at java.lang.ref.NativeReferenceQueue.await(java.base@21.0.1/NativeReferenceQueue.java:48)
        at java.lang.ref.ReferenceQueue.remove0(java.base@21.0.1/ReferenceQueue.java:158)
        at java.lang.ref.NativeReferenceQueue.remove(java.base@21.0.1/NativeReferenceQueue.java:89)
        - locked <0x0000000400809ec8> (a java.lang.ref.NativeReferenceQueue$Lock)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@21.0.1/Finalizer.java:173)

"Signal Dispatcher" #11 [23555] daemon prio=9 os_prio=31 cpu=0.15ms elapsed=7.86s tid=0x000000014e867200 nid=23555 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #12 [23811] daemon prio=9 os_prio=31 cpu=0.14ms elapsed=7.86s tid=0x000000013e894000 nid=23811 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Deflation Thread" #13 [42755] daemon prio=9 os_prio=31 cpu=0.46ms elapsed=7.86s tid=0x000000013e894800 nid=42755 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #14 [42499] daemon prio=9 os_prio=31 cpu=280.83ms elapsed=7.86s tid=0x000000013e896e00 nid=42499 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #17 [41987] daemon prio=9 os_prio=31 cpu=231.92ms elapsed=7.86s tid=0x000000012e808200 nid=41987 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Notification Thread" #18 [41475] daemon prio=9 os_prio=31 cpu=0.03ms elapsed=7.85s tid=0x000000013e897600 nid=41475 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #19 [24835] daemon prio=8 os_prio=31 cpu=0.64ms elapsed=7.85s tid=0x000000013e814400 nid=24835 waiting on condition  [0x000000016f556000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.1/Native Method)
        - parking to wait for  <0x0000000400805100> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@21.0.1/LockSupport.java:269)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@21.0.1/AbstractQueuedSynchronizer.java:1847)
        at java.lang.ref.ReferenceQueue.await(java.base@21.0.1/ReferenceQueue.java:71)
        at java.lang.ref.ReferenceQueue.remove0(java.base@21.0.1/ReferenceQueue.java:143)
        at java.lang.ref.ReferenceQueue.remove(java.base@21.0.1/ReferenceQueue.java:218)
        at jdk.internal.ref.CleanerImpl.run(java.base@21.0.1/CleanerImpl.java:140)
        at java.lang.Thread.runWith(java.base@21.0.1/Thread.java:1596)
        at java.lang.Thread.run(java.base@21.0.1/Thread.java:1583)
        at jdk.internal.misc.InnocuousThread.run(java.base@21.0.1/InnocuousThread.java:186)

"Reference Reaper #1" #21 [40707] daemon prio=5 os_prio=31 cpu=1.58ms elapsed=7.71s tid=0x000000014e81b400 nid=40707 waiting on condition  [0x000000016fb7a000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.1/Native Method)
        - parking to wait for  <0x0000000400818c40> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@21.0.1/LockSupport.java:371)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@21.0.1/AbstractQueuedSynchronizer.java:519)
        at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@21.0.1/ForkJoinPool.java:3780)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@21.0.1/ForkJoinPool.java:3725)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@21.0.1/AbstractQueuedSynchronizer.java:1707)
        at java.lang.ref.ReferenceQueue.await(java.base@21.0.1/ReferenceQueue.java:67)
        at java.lang.ref.ReferenceQueue.remove0(java.base@21.0.1/ReferenceQueue.java:158)
        at java.lang.ref.ReferenceQueue.remove(java.base@21.0.1/ReferenceQueue.java:234)
        at io.smallrye.common.ref.References$ReaperThread.run(References.java:58)

"executor-thread-2" #24 [26115] daemon prio=5 os_prio=31 cpu=0.19ms elapsed=7.47s tid=0x000000013f215a00 nid=26115 waiting on condition  [0x000000016fd86000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.1/Native Method)
        - parking to wait for  <0x0000000400813d28> (a org.jboss.threads.EnhancedQueueExecutor)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@21.0.1/LockSupport.java:269)
        at org.jboss.threads.EnhancedQueueExecutor$PoolThreadNode.park(EnhancedQueueExecutor.java:2299)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1565)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at java.lang.Thread.runWith(java.base@21.0.1/Thread.java:1596)
        at java.lang.Thread.run(java.base@21.0.1/Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)

"Thread-3" #25 [26627] prio=5 os_prio=31 cpu=1.96ms elapsed=7.44s tid=0x000000013e98a200 nid=26627 waiting on condition  [0x000000016ff92000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.1/Native Method)
        - parking to wait for  <0x000000040080a158> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(java.base@21.0.1/LockSupport.java:221)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@21.0.1/AbstractQueuedSynchronizer.java:754)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@21.0.1/AbstractQueuedSynchronizer.java:1099)
        at java.util.concurrent.CountDownLatch.await(java.base@21.0.1/CountDownLatch.java:230)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:214)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:154)
        at javafx.application.Application.launch(Application.java:233)
        at io.quarkiverse.fx.QuarkusFxApplication.lambda$run$0(QuarkusFxApplication.java:30)
        at io.quarkiverse.fx.QuarkusFxApplication$$Lambda/0x00000008002024d0.run(Unknown Source)
        at java.lang.Thread.runWith(java.base@21.0.1/Thread.java:1596)
        at java.lang.Thread.run(java.base@21.0.1/Thread.java:1583)

"JavaFX-Launcher" #26 [40451] prio=5 os_prio=31 cpu=25.33ms elapsed=7.44s tid=0x000000014e98c200 nid=40451 waiting on condition  [0x00000002a8206000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.1/Native Method)
        - parking to wait for  <0x0000000400822a18> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(java.base@21.0.1/LockSupport.java:221)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@21.0.1/AbstractQueuedSynchronizer.java:754)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@21.0.1/AbstractQueuedSynchronizer.java:1099)
        at java.util.concurrent.CountDownLatch.await(java.base@21.0.1/CountDownLatch.java:230)
        at com.sun.javafx.application.PlatformImpl.runAndWait(PlatformImpl.java:494)
        at com.sun.javafx.application.PlatformImpl.runAndWait(PlatformImpl.java:468)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:832)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at com.sun.javafx.application.LauncherImpl$$Lambda/0x0000000800203dc8.run(Unknown Source)
        at java.lang.Thread.runWith(java.base@21.0.1/Thread.java:1596)
        at java.lang.Thread.run(java.base@21.0.1/Thread.java:1583)

"QuantumRenderer-0" #27 [40195] daemon prio=5 os_prio=31 cpu=28.18ms elapsed=7.42s tid=0x000000010387ac00 nid=40195 waiting on condition  [0x00000002a8412000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.1/Native Method)
        - parking to wait for  <0x000000040080a6c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@21.0.1/LockSupport.java:371)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@21.0.1/AbstractQueuedSynchronizer.java:519)
        at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@21.0.1/ForkJoinPool.java:3780)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@21.0.1/ForkJoinPool.java:3725)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@21.0.1/AbstractQueuedSynchronizer.java:1707)
        at java.util.concurrent.LinkedBlockingQueue.take(java.base@21.0.1/LinkedBlockingQueue.java:435)
        at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@21.0.1/ThreadPoolExecutor.java:1070)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@21.0.1/ThreadPoolExecutor.java:1130)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@21.0.1/ThreadPoolExecutor.java:642)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
        at java.lang.Thread.runWith(java.base@21.0.1/Thread.java:1596)
        at java.lang.Thread.run(java.base@21.0.1/Thread.java:1583)

"InvokeLaterDispatcher" #29 [31495] daemon prio=5 os_prio=31 cpu=0.57ms elapsed=7.39s tid=0x000000013ecbe600 nid=31495 in Object.wait()  [0x00000002a861e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait0(java.base@21.0.1/Native Method)
        - waiting on <0x0000000400805340> (a java.lang.StringBuilder)
        at java.lang.Object.wait(java.base@21.0.1/Object.java:366)
        at java.lang.Object.wait(java.base@21.0.1/Object.java:339)
        at com.sun.glass.ui.InvokeLaterDispatcher.run(InvokeLaterDispatcher.java:126)
        - locked <0x0000000400805340> (a java.lang.StringBuilder)

"JavaFX Application Thread" #30 [259] prio=5 os_prio=31 cpu=246.79ms elapsed=7.39s tid=0x000000013ecbee00 nid=259 waiting on condition  [0x000000016d0e9000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@21.0.1/Native Method)
        - parking to wait for  <0x0000000401970b88> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(java.base@21.0.1/LockSupport.java:221)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@21.0.1/AbstractQueuedSynchronizer.java:754)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@21.0.1/AbstractQueuedSynchronizer.java:1099)
        at java.util.concurrent.CountDownLatch.await(java.base@21.0.1/CountDownLatch.java:230)
        at io.quarkiverse.fx.FxStartupLatch.await(FxStartupLatch.java:17)
        at io.quarkiverse.fx.RunOnFxThreadInterceptor.runOnFxThread(RunOnFxThreadInterceptor.java:30)
        at io.quarkiverse.fx.RunOnFxThreadInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at tck.jakarta.rewrite.fx.AppController_Subclass.setStatus(Unknown Source)
        at tck.jakarta.rewrite.fx.AppController.initialize(AppController.java:121)
        at java.lang.invoke.LambdaForm$DMH/0x000000080033c800.invokeVirtual(java.base@21.0.1/LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/0x000000080033d000.invoke(java.base@21.0.1/LambdaForm$MH)
        at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@21.0.1/Invokers$Holder)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@21.0.1/DirectMethodHandleAccessor.java:153)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@21.0.1/DirectMethodHandleAccessor.java:103)
        at java.lang.reflect.Method.invoke(java.base@21.0.1/Method.java:580)
        at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:72)
        at java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.base@21.0.1/DirectMethodHandle$Holder)
        at java.lang.invoke.LambdaForm$MH/0x000000080033c400.invoke(java.base@21.0.1/LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/0x00000008000ccc00.invokeExact_MT(java.base@21.0.1/LambdaForm$MH)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@21.0.1/DirectMethodHandleAccessor.java:156)
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@21.0.1/DirectMethodHandleAccessor.java:103)
        at java.lang.reflect.Method.invoke(java.base@21.0.1/Method.java:580)
        at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:270)
        at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2688)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2547)
        at io.quarkiverse.fx.views.FxViewRepository.setupViews(FxViewRepository.java:97)
        at io.quarkiverse.fx.views.FxViewRepository_Observer_setupViews_Xy6Iqgh9TfvvZg_aoW9TsMksxXQ.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
        at io.quarkiverse.fx.FxApplication.start(FxApplication.java:25)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
        at com.sun.javafx.application.LauncherImpl$$Lambda/0x000000080023d870.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
        at com.sun.javafx.application.PlatformImpl$$Lambda/0x000000080023ef90.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at com.sun.javafx.application.PlatformImpl$$Lambda/0x000000080023d430.run(Unknown Source)
        at java.security.AccessController.executePrivileged(java.base@21.0.1/AccessController.java:778)
        at java.security.AccessController.doPrivileged(java.base@21.0.1/AccessController.java:400)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl$$Lambda/0x000000080023f3c8.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

"PulseTimer-CVDisplayLink thread" #32 [52995] daemon prio=5 os_prio=31 cpu=22.72ms elapsed=7.32s tid=0x000000014ea02200 nid=52995 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=31 cpu=4.77ms elapsed=7.90s tid=0x000000013e607990 nid=17667 runnable  

"GC Thread#0" os_prio=31 cpu=4.59ms elapsed=7.91s tid=0x000000013e706650 nid=20995 runnable  

"GC Thread#1" os_prio=31 cpu=4.59ms elapsed=7.29s tid=0x000000012e70cee0 nid=54275 runnable  

"GC Thread#2" os_prio=31 cpu=2.58ms elapsed=7.29s tid=0x000000012e70d450 nid=76803 runnable  

"GC Thread#3" os_prio=31 cpu=4.43ms elapsed=7.30s tid=0x000000012e70d9c0 nid=76547 runnable  

"GC Thread#4" os_prio=31 cpu=4.02ms elapsed=7.30s tid=0x000000012e70df30 nid=76291 runnable  

"GC Thread#5" os_prio=31 cpu=4.29ms elapsed=7.30s tid=0x000000012e70e4a0 nid=55555 runnable  

"GC Thread#6" os_prio=31 cpu=4.79ms elapsed=7.30s tid=0x0000000103707340 nid=55811 runnable  

"GC Thread#7" os_prio=31 cpu=4.40ms elapsed=7.30s tid=0x00000001037078b0 nid=56323 runnable  

"GC Thread#8" os_prio=31 cpu=4.66ms elapsed=7.30s tid=0x000000013e722b80 nid=56579 runnable  

"G1 Main Marker" os_prio=31 cpu=0.08ms elapsed=7.91s tid=0x000000013e706df0 nid=20483 runnable  

"G1 Conc#0" os_prio=31 cpu=1.82ms elapsed=7.91s tid=0x000000013e707760 nid=13315 runnable  

"G1 Conc#1" os_prio=31 cpu=0.91ms elapsed=7.29s tid=0x000000014e689120 nid=75523 runnable  

"G1 Refine#0" os_prio=31 cpu=0.01ms elapsed=7.91s tid=0x000000013f08c800 nid=19459 runnable  

"G1 Service" os_prio=31 cpu=0.49ms elapsed=7.91s tid=0x000000013e709f40 nid=19203 runnable  

"VM Periodic Task Thread" os_prio=31 cpu=5.05ms elapsed=7.91s tid=0x000000013e604a80 nid=18691 waiting on condition  

JNI global refs: 24, weak refs: 0

Heap
 garbage-first heap   total 81920K, used 28800K [0x0000000400000000, 0x0000000800000000)
  region size 8192K, 3 young (24576K), 1 survivors (8192K)
 Metaspace       used 26632K, committed 26944K, reserved 1114112K
  class space    used 3211K, committed 3328K, reserved 1048576K
```

**Comment by starksm64** [comment]
Note I replaced the thread dump with one from running the app on the command line as the quarkus:run output was messed up.

**Comment by CodeSimcoe** [comment]
Hello @starksm64,
I managed to isolate and reproduce the deadlock issue on my own.

This has to do with the startup lifecycle.
`FXViews` are created before latch is released and `@RunOnFxThread` waits for the latch itself.

In the latest version, i now have 3 lifecycle events in sequence :
1. app start (`Application` is available)
2. fx view loading
3. post start and latch release

I propose to release latch at step 1.

**Comment by CodeSimcoe** [comment]
#61

**Comment by CodeSimcoe** [comment]
Closing issue, feel free to reopen if needed
